name: check upytorch build size
inputs:
  name:
    required: true
runs:
  using: "composite"
  steps:
    - name: show binary size
      run: |
        mkdir -p output_size
        strip build/upytorch -o build/upytorch.strip
        tar zcvf build/upytorch.tar.gz build/upytorch.strip
        ls -la build/upytorch* | tee output_size/size.txt
        cp build/upytorch.strip build_result
      shell: bash

    - name: run bloaty
      run: |
        UNAME=$(uname -s)
        if [ "$UNAME" != "Darwin" ]; then
          exit 0
        fi
        echo
        echo "Run bloaty..."
        brew install bloaty >log 2>err || (cat log && cat err)
        make clean >log 2>err || (cat log && cat err)
        scripts/run_bloaty.sh >log 2>err || (cat log && cat err)
        cat output_size/bloaty_units.txt
      shell: bash
