 0
[ CPUBoolType{1} ]
 0
[ CPULongType{1} ]
 0
[ CPUDoubleType{1} ]
 0
[ CPUByteType{1} ]
 0
[ CPUCharType{1} ]
 0
[ CPUDoubleType{1} ]
 0
[ CPUDoubleType{1} ]
 0
[ CPUFloatType{1} ]
 0
[ CPUFloatType{1} ]
 0
[ CPUIntType{1} ]
 0
[ CPUIntType{1} ]
 0
[ CPULongType{1} ]
 0
[ CPULongType{1} ]
 0
[ CPUShortType{1} ]
 0
[ CPUShortType{1} ]
 0
[ CPUHalfType{1} ]
 0
[ CPUHalfType{1} ]
 0
[ CPUBoolType{1} ]
 0
[ CPUBFloat16Type{1} ]
