name: check framework overhead
inputs:
  name:
    required: true
runs:
  using: "composite"
  steps:
    - name: install valgrind
      run: |
        sudo apt-get update && sudo apt-get install -y valgrind
      shell: bash

    - name: run valgrind
      run: |
        export NAME=${{ inputs.name }}
        export BIN=$(pwd)/build/upytorch
        scripts/run_valgrind.sh run_simple_add
      shell: bash
