name: check framework overhead
inputs:
  name:
    required: true
  binary:
    required: false
runs:
  using: "composite"
  steps:
    - name: install valgrind
      run: |
        sudo apt-get update && sudo apt-get install -y valgrind
      shell: bash

    - name: run valgrind
      run: |
        export NAME=${{ inputs.name }}
        if [ -z "${{ inputs.binary }}" ]; then
          export BIN=$(pwd)/build/upytorch
        else
          export BIN="${{ inputs.binary }}"
        fi
        scripts/run_valgrind.sh run_simple_add
      shell: bash
