name: check framework overhead
inputs:
  name:
    required: true
  binary:
    required: false
runs:
  using: "composite"
  steps:
    - name: install valgrind
      run: |
        sudo apt-get update -y > log.txt 2> err.txt || (cat log.txt && cat err.txt)
        sudo apt-get install valgrind -y > log.txt 2> err.txt || (cat log.txt && cat err.txt)
      shell: bash

    - name: run walltime
      run: |
        export NAME=${{ inputs.name }}
        if [ -z "${{ inputs.binary }}" ]; then
          export BIN=$(pwd)/build/upytorch
        else
          export BIN="${{ inputs.binary }}"
        fi
        mkdir -p output_perf
        scripts/run_benchmark.sh | tee output_perf/${NAME}_benchmark.txt
      shell: bash

    - name: run valgrind
      run: |
        export NAME=${{ inputs.name }}
        if [ -z "${{ inputs.binary }}" ]; then
          export BIN=$(pwd)/build/upytorch
        else
          export BIN="${{ inputs.binary }}"
        fi
        mkdir -p output_perf
        scripts/run_valgrind.sh run_dummy | tee -a output_perf/${NAME}_valgrind.txt
        scripts/run_valgrind.sh run_simple_add | tee -a output_perf/${NAME}_valgrind.txt
      shell: bash
