- aten::adaptive_avg_pool2d.out
- aten::adaptive_avg_pool2d
- aten::add.Tensor
- aten::add_.Tensor
- aten::add.out
- aten::addmm.out
- aten::addmm
- aten::addmm_
- aten::convolution
- aten::conv2d
- aten::conv_transpose2d.input
- aten::dropout
- aten::dropout_
- aten::empty.memory_format
- aten::empty.out
- aten::empty_like
- aten::eye
- aten::eye.m
- aten::eye.out
- aten::eye.m_out
- aten::flatten.using_ints
- aten::matmul
- aten::max_pool2d
- aten::mm
- aten::mm.out
- aten::mul.Tensor
- aten::mul_.Tensor
- aten::mul.out
- aten::mul.Scalar
- aten::mul_.Scalar
- aten::ones
- aten::ones.out
- aten::ones_like
- aten::rand
- aten::rand.out
- aten::relu
- aten::relu_
- aten::softmax.int
- aten::sum
- aten::t
- aten::t_
- aten::zeros
- aten::zeros.out
- aten::zeros_like

- aten::dummy
- aten::dummy_
- aten::dummy.out
