name: dynamically linked prebuilt libtorch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_platform-macos_libtorch-prebuilt_ops-dev:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: checkout submodules
      run: git submodule update --init --recursive micropython pytorch

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install pip dependency
      run: |
        python3 -m pip install --upgrade pip
        pip install -r pytorch/requirements.txt

    - name: make
      run: LIBTORCH=prebuilt make

    - name: test
      run: LIBTORCH=prebuilt make test

    - name: show binary size
      run: |
        strip build/upytorch -o build/upytorch.strip
        tar zcvf build/upytorch.tar.gz build/upytorch.strip
        ls -la build/upytorch*

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: platform-macos.libtorch-prebuilt.ops-dev
        path: build/upytorch.strip

  test_platform-linux_libtorch-prebuilt_ops-dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: checkout submodules
      run: git submodule update --init --recursive micropython pytorch

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install pip dependency
      run: |
        python3 -m pip install --upgrade pip
        pip install -r pytorch/requirements.txt

    - name: make
      run: LIBTORCH=prebuilt make

    - name: test
      run: LIBTORCH=prebuilt make test

    - name: show binary size
      run: |
        strip build/upytorch -o build/upytorch.strip
        tar zcvf build/upytorch.tar.gz build/upytorch.strip
        ls -la build/upytorch*

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: platform-linux.libtorch-prebuilt.ops-dev
        path: build/upytorch.strip
