name: Manual Build

on:
  # This workflow is too slow to run on every PR/Push!

  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      git-ref:
        description: PyTorch Git Ref (Optional)
        required: false

jobs:

###############################################################################
#
#                     dynamically linked local libtorch
#
###############################################################################

  platform-ubuntu_libtorch-local_ops-dev-with-dummy:

    runs-on: ubuntu-latest
    env:
      LIBTORCH: local
      OP_SELECTION_YAML: tools/dev_with_dummy.yaml

    steps:
    - uses: actions/checkout@v2

    - name: checkout submodules
      run: |
        git submodule update --init --recursive micropython pytorch
        echo "PYTORCH_REV=$(cd pytorch; git rev-parse HEAD)" >> $GITHUB_ENV

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # No enough storage for ccache!
    #
    # - name: install ccache
    #   run: |
    #     sudo apt install -y ccache
    #
    # - name: cache local built libtorch
    #   uses: actions/cache@v2
    #   env:
    #     cache-name: cache-local-built-libtorch-v1
    #   with:
    #     path: ~/.ccache
    #     key: ${{ matrix.config.name }}-${{ runner.os }}-${{ env.cache-name }}-${{ env.PYTORCH_REV }}

    - uses: ./.github/actions/setup_libtorch_build_env

    - name: make & test
      run: |
        # export PATH="/usr/lib/ccache:$PATH"
        # ccache -s
        # echo "gcc -> $(which gcc)"
        make test
        # ccache -s

    - name: check python3 perf (dynamically linked with the locally built standard libtorch)
      uses: ./.github/actions/check_perf
      with:
        name: py3.local
        binary: python3

    - name: check micropython perf (dynamically linked with the locally built standard libtorch)
      uses: ./.github/actions/check_perf
      with:
        name: upy.local
